# Generated by Django 2.0.5 on 2018-10-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20181003_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannersimg', models.ImageField(upload_to='%Y%m%d')),
                ('link_to', models.URLField(null=True)),
                ('postion', models.IntegerField()),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
