# Generated by Django 2.0.5 on 2018-09-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
